perinatal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *


urlpatterns = [
    # BASIC VIEW -------------------------------------------------------------------------------------------------
    path('', ListPerinatalView.as_view(), name='list_perinatal_records'),
    path('create/', CreatePerinatalView.as_view(), name='create_perinatal_record'),
    path('update/<int:pk>',UpdatePerinatalView.as_view(), name='update_perinatal_record'),
    path('<int:pk>/', DetailPerinatalView.as_view(), name='detail_perinatal_record'),
    path('<int:pk>/pdf/', PreviewPerinatalPDFView.as_view(), name='preview_perinatal_pdf'),
    path('<int:pk>/pdf/download/', DownloadPerinatalPDFView.as_view(), name='download_perinatal_pdf')
    #path('test/', test, name='test'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("perinatal/", include("perinatal.urls")),
]

perinatal/models.py
from datetime import date
from django.db import models
from .validators import *
from .manager import *

from django.db.models.signals import pre_save
from django.dispatch import receiver


class EstadoCivil(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class EstadoCivil(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion

class Etnia(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion


class Anticonceptivos(models.Model):
    descripcion = models.CharField(max_length=50)

    def __str__(self):
        return self.descripcion


class HcpHcPerinatal(models.Model):
    CHOICES_SI_NO = (
        ('S', 'Si'),
        ('N', 'No')
    )

    CHOICES_ESTUDIOS = (
        ('Ninguno', 'Ninguno'),
        ('Primario', 'Primario'),
        ('Secundario', 'Secundario'),
        ('Universitario', 'Universitario')
    )

    CHOICES_ULTIMO_PREVIO = (
        ('n/c','n/c'),
        ('<2500g','<2500g'),
        ('normal','normal'),
        ('>=4000g','>=4000g')
    )

    hcp_id = models.BigAutoField(primary_key=True) #~VERIFICAR! ESTE CAMPO ERA CHARFIELD
    hcp_personaid = models.CharField(max_length=15, null=True, blank=True)
    hcp_nrodocumento_0019 = models.CharField(max_length=20, null=True, blank=True, help_text="Nro de Documento")
    hcp_telefono_0005 = models.SmallIntegerField(null=True, blank=True, help_text="Teléfono")
    hcp_fechanacimiento_0006 = models.DateField(validators=[validacion_fecha_nacimiento], null=True, blank=True, help_text="Fecha de nacimiento")
    hcp_edad_0009 = models.SmallIntegerField(validators=[validacion_rango_edad], null=True, blank=True, help_text="Edad")
    hcp_alertaedad_0010 = models.BooleanField(blank=True)
    hcp_etnia_0011 = models.ForeignKey(Etnia, on_delete=models.CASCADE, null=True, blank=True, help_text="Etnia")
    hcp_alfabeta_0012 = models.CharField(max_length=1, choices=CHOICES_SI_NO, blank=True, help_text="Alfabeta")
    hcp_estudios_0013 = models.CharField(max_length=40, choices=CHOICES_ESTUDIOS, null=True, blank=True, help_text="Estudios")
    hcp_aniosmayornivel_0014 = models.SmallIntegerField(null=True, blank=True, help_text="Años mayor nivel")
    hcp_estadocivil_0015 = models.CharField(max_length=40, null=True, blank=True, help_text="Estado civil")
    hcp_vivesola_0016 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Vive Sola")
    hcp_establecimientocontrolid_0017 = models.CharField(max_length=40, null=True, blank=True, help_text="Lugar de Control Prenatal")
    hcp_establecimientopartoid_0018 = models.CharField(max_length=40, null=True, blank=True, help_text="Lugar del Parto")
    hcp_ant_tbcfamiliar_0020 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="TBC Familiar")
    hcp_ant_tbcpersonal_0021 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="TBC Personal")
    hcp_ant_diabetfamiliar_0022 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Diabetes Familiar")
    hcp_ant_diabetpersonal_0023 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Diabetes Personal")
    hcp_ant_hipertenfamiliar_0024 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Hipertensión Familiar")
    hcp_ant_hipertenpersonal_0025 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Hipertensión Personal")
    hcp_ant_preeclampsiafamiliar_0026 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Preeclampsia Familiar")
    hcp_ant_preeclampsiapersonal_0027 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Preeclampsia Personal")
    hcp_ant_eclampsiafamiliar_0028 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Eclampsia Familiar")
    hcp_ant_eclampsiapersonal_0029 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Eclampsia Personal")
    hcp_ant_otracondmedicafamiliar_0030 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Otras Cond. Medicas Familiar")
    hcp_ant_otracondmedicapersonal_0031 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Otras Cond. Medicas Personal")
    hcp_ant_cgiagenitourinaria_0032 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Cgia genito-urinaria")
    hcp_ant_infertilidad_0033 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Infertilidad")
    hcp_ant_nefropatia_0035 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Cardiopatía")
    hcp_ant_cardiopat_0034 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Nefropatia")
    hcp_ant_violencia_0036 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Violencia")
    hcp_ant_vih_0432 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="VIH+")
    hcp_ant_ultimoprevio_0038 = models.CharField(max_length=40, choices=CHOICES_ULTIMO_PREVIO, null=True, blank=True, help_text="Ultimo Previo")
    hcp_ant_antecedentegemelar_0039 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Antecedente Gemelar")
    hcp_ant_gestasprevia_0040 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad Gestas Previas")
    hcp_ant_abortos_0041 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad de Abortos")
    hcp_ant_partvaginales_0042 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad de Partos Vaginales")
    hcp_ant_nacidovivo_0043 = models.SmallIntegerField(null=True, blank=True, help_text="Cant. de Nacidos Vivos ")
    hcp_ant_viven_0044 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad de hijos que viven")
    hcp_ant_tresabortosconsecu_0045 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="3 Abortos consecutivos")
    hcp_ant_cesareas_0047 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad de Césareas")
    hcp_ant_embectopico_0409 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad Embarazo Ectópico")
    hcp_ant_partosprevios_0046 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad Partos Previos")
    hcp_ant_nacidomuerto_0048 = models.SmallIntegerField(null=True, blank=True, help_text="Cantidad Nacidos Muertos")
    hcp_ant_muertoantessemana_0049 = models.SmallIntegerField(null=True, blank=True, help_text="Cant. de Muertos Primera Semana")
    hcp_ant_muertodespsemana_0050 = models.SmallIntegerField(null=True, blank=True, help_text="Cant. de Muertos Desp. de la Primera Semana.")
    hcp_ant_fechaembarazoanterior_0051 = models.DateField(null=True, blank=True, help_text="Fecha de Fin Embarazo Anterior")
    hcp_ant_finmenosdeunanio_0052 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Menor a 1 año")
    hcp_ant_embarazoplaneado_0053 = models.CharField(max_length=1, choices=CHOICES_SI_NO, null=True, blank=True, help_text="Embarazo Planeado")
    hcp_ant_fracasoanticonceptivoid_0054 = models.SmallIntegerField(null=True, blank=True, help_text="Fracaso Anticonceptivo")
    #----AUDITORIA-----
    hcp_fechadeapertura = models.DateTimeField(null=True, blank=True)
    hcp_idusuarioapertura = models.CharField(max_length=40, null=True, blank=True)
    hcp_fechacierre = models.DateTimeField(null=True, blank=True)
    hcp_idusuariocierre = models.CharField(max_length=40, null=True, blank=True)
    hcp_usuariobaja = models.CharField(max_length=40, null=True, blank=True)
    hcp_fechabaja = models.DateTimeField(null=True, blank=True)
    hcp_motivobaja = models.CharField(max_length=60, null=True, blank=True)
    hcp_aperturaestableid = models.CharField(max_length=40, null=True, blank=True)
    hcp_bajaestableid = models.CharField(max_length=40, null=True, blank=True)
    hcp_cierraestableid = models.CharField(max_length=40, null=True, blank=True)
    hcp_fechamodificacion = models.DateTimeField(null=True, blank=True)
    hcp_usuariomodificacion = models.CharField(max_length=40, null=True, blank=True)
    #----FIN DE AUDITORIA---
    anticonceptivo = models.ForeignKey(Anticonceptivos, models.DO_NOTHING,null=True,blank=True)

    objects = HcpHcPerinatalManager()

    def calcular_edad(self):
        hoy = date.today()
        fecha_nacimiento = self.hcp_fechanacimiento_0006
        edad = hoy.year - fecha_nacimiento.year - (
                    (hoy.month, hoy.day) < (fecha_nacimiento.month, fecha_nacimiento.day))
        self.hcp_edad_0009 = edad

    def save(self, *args, **kwargs):
        self.calcular_edad()
        if self.hcp_edad_0009 < 15 or self.hcp_edad_0009 > 35:
            self.hcp_alertaedad_0010 = True
        else:
            self.hcp_alertaedad_0010 = False
        super(HcpHcPerinatal, self).save(*args, **kwargs)

    class Meta:
        db_table = 'hcp_hcperinatalsti'

    def __str__(self):
        return f'{self.hcp_id}'
    
@receiver(pre_save, sender=HcpHcPerinatal)
def pre_save_HcpHcPerinatal(sender, instance, **kwargs):
    '''
    Realiza operaciones previas a la instanciacion de un objeto HcpHcPerinatal
    '''
    validacion_informacion_estudios(instance)
    #validacion_gestas_previas(gesta_actual, gestas_previas)
    validacion_fecha_emb_anterior(instance.hcp_ant_fechaembarazoanterior_0051, instance.hcp_ant_gestasprevia_0040)

perinatal/views.py
#from django.http import request
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView

from .forms import *
from .models import *

from .gx_auth import show_cookie_view


class ListPerinatalView(ListView):
    # model = None
    # context_object_name = 'test'
    # queryset = []
    # template_name = 'index.html'
    pass

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CreatePerinatalView(CreateView):

    template_name = 'new-registry-copy.html'
    form_class = HcpHcPerinatalForm
    model = HcpHcPerinatal
    success_url = reverse_lazy('create_perinatal_record')

    def get(self, request, *args, **kwargs):
        # Accede al objeto request aquí
        cookie_data = show_cookie_view(request)
        print(cookie_data)
        return super().get(request, *args, **kwargs)

class UpdatePerinatalView(UpdateView):
    template_name = 'new-registry-copy.html'
    form_class = HcpHcPerinatalForm
    model = HcpHcPerinatal
    success_url = reverse_lazy('create_perinatal_record')
    

class DetailPerinatalView(View):
    pass


class PreviewPerinatalPDFView(View):
    pass


class DownloadPerinatalPDFView(View):
    pass


# def test(request):
#     context = {
#         'form': TestForm(),
#     }
#     return render(request, 'test.html', context)

perinatal/templates/DatosGenerales_form.html
{% load static %}


<!-- ===============================================-->
<!--       Pestañas de etapa                        -->
<!-- ===============================================-->


<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="tab-datos-generales" data-bs-toggle="tab" data-bs-target="#datos-generales"
      type="button" role="tab" aria-controls="datos-generales" aria-selected="true">Datos generales</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="tab-datos-complementarios" data-bs-toggle="tab" data-bs-target="#datos-complementarios"
      type="button" role="tab" aria-controls="datos-complementarios" aria-selected="false">Datos
      complementarios</button>
  </li>
</ul>

<!-- ===============================================-->
<!--       Contenido de pestañas                    -->
<!-- ===============================================-->

<!-- Datos Generales-->
<div class="tab-content" id="datos-generales-content">
  <div class="tab-pane fade show active" id="datos-generales" role="tabpanel" aria-labelledby="datos-generales">
    <div class="tab-pane container active" id="datos-demograficos" role="tabpanel">
      <span>
        <div class="container my-2">
          <small class="text-body-secondary">Información personal del paciente</small>
          <hr class="my-4">
        </div>
      </span>
    </div>
    <div class="row justify-content-center d-flex">
      <div class="col">
        <div class="form-floating mb-3">
          {{ form.hcp_nrodocumento_0019 }}
          <label for="id_hcp_nrodocumento_0019">Numero de Documento</label>
        </div>
      </div>
      <div class="col">
        <div class="form-floating mb-3">
          {{ form.hcp_nrodocumento_0019 }}
          <label for="id_hcp_telefono_0005">Telefono de Contacto</label>
        </div>
      </div>
    </div>
    <div class="row justify-content-center d-flex">
      <div class="col m-3">
        {{ form.hcp_fechanacimiento_0006 }}
      </div>
      <div class="col m-3">
        {{ form.hcp_edad_0009 }}
        <span id="msg-alerta-edad" style="display: none;">
          <p class="text-danger m-0 p-0">Edad en rangos de alerta</p>
        </span>
      </div>
    </div>
  </div>
</div>

<!--Datos complementarios-->
<div class="tab-content" id="datos-complementarios-content">
  <div class="tab-pane fade" id="datos-complementarios" role="tabpanel" aria-labelledby="datos-complementarios">
    <div class="tab-pane container">
      <!--<span style="color:darkgrey">step 1/8</span>-->
      <div class="container my-2">
        <span>
          <small class="text-body-secondary">Información complementaria del paciente</small>
          <hr class="my-4">
        </span>
      </div>
    </div>
    <div class="row justify-content-center d-flex">
      <div class="col">
        <div class="control mb-2 form-floating">
          {{ form.hcp_etnia_0011 }}
          <label for="id_hcp_etnia_0011">Etnia</label>
        </div>
      </div>
      <div class="col">
        <div class="control mb-2 form-floating">
          {{ form.hcp_estadocivil_0015 }}
          <label for="id_hcp_estadocivil_0015">Estado Civil</label>
        </div>
      </div>
      <div class="col">
        <div class="control mb-2 form-floating">
          {{ form.hcp_vivesola_0016 }}
          <label for="id_hcp_vivesola_0016">Vive Sola</label>
        </div>
      </div>
    </div>
    <div class="row justify-content-center d-flex">
      <div class="col">
        <div class="card m-2" style="width: auto;">
          <div class="card-body">
            <h5 class="card-subtitle mb-2">Alfabeta</h5>
            <div class="alfabeta-check-group">
              <div class="control mb-2">
                
                <div class="form-check">
                  {{ form.hcp_alfabeta_0012 }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card m-2" style="width: auto;">
          <div class="card-body">
            
            <h5 class="card-subtitle mb-2">Estudios</h5>
            <div class="alfabeta-check-group">
              <div class="control mb-2">
                <div class="form-check">
                  {% for field in form.hcp_estudios_0013 %}
                    {{ field }}
                    {{ field.label_tag }}
                    <br>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center d-flex">
      <div class="col">
        <div class="form-floating mb-3">
          {{form.hcp_aniosmayornivel_0014}}
          <label for="id_hcp_aniosmayornivel_0014">Años en el mayor nivel educativo</label>
        </div>
      </div>
    </div>
  </div>
</div>

perinatal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- {% static 'assets/css/bootstrap.min.css' %}  -->
    <!-- {% static 'assets/css/bootstrap.min.css' %}  -->

    <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/icon/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    {% block head %}
    {% endblock %}
    <title>SIP Plus</title>
</head>

<body>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <!-- {% static 'assets/js/bootstrap.bundle.min.js' %}  -->
    <script src={% static 'assets/js/check-controls.js' %}></script>
    {% block script %}
    {% endblock %}
</body>
</html>

perinatal/templates/test.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- {% static 'assets/css/bootstrap.min.css' %}  -->

    <link rel="shortcut icon" type="image/x-icon" href="{% static '/assets/icon/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
    <title>SIP Plus</title>
</head>
<body>

    <!-- Inicio del bloque Content -->
    <section class="container py-4">
        <!-- Header -->
        <div class="row">
            <div class="col" style="border-bottom: 1px solid #EAEAEA;">
                <div class="container-fluid">
                    <div class="row">
                        <h2>Historia Clinica Perinatal</h2>
                    </div>
                    <div class="row">
                        <span style="color:darkgrey">Completa los campos para realizar la carga del registro.</span>
                    </div>
                    {% endfor %}
                    <!-- Submit button -->
                    <div class="d-flex">
                        <button type="button" class="btn btn-secondary btn-block flex-fill me-2 mb-4"
                                data-bs-dismiss="modal">Cancelar
                        </button>
                        <button type="submit" class="btn btn-primary btn-block flex-fill mb-4">Aceptar</button>
                    </div>
                </div>
            </form>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous">
    </script>

    <script src="{% static 'assets/js/validators.js' %}"></script>
</body>
</html>